# Generated by Django 4.2 on 2023-07-04 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('correo', models.EmailField(max_length=254)),
                ('fono', models.IntegerField()),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, null=True)),
                ('descripcion', models.TextField(default='---')),
                ('foto', models.ImageField(null=True, upload_to='especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('edad', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('foto', models.ImageField(null=True, upload_to='mecanico')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web_Taller_Mecánico.especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('precio', models.IntegerField(default=1000)),
                ('descripcion', models.TextField()),
                ('foto', models.ImageField(null=True, upload_to='producto')),
            ],
        ),
        migrations.CreateModel(
            name='regAte',
            fields=[
                ('idAtencion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=45)),
                ('descAte', models.TextField()),
                ('materiales', models.TextField()),
                ('fecha', models.DateField()),
                ('foto', models.ImageField(null=True, upload_to='atenciones')),
                ('publicar', models.BooleanField(default=False)),
                ('rutMeca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Web_Taller_Mecánico.mecanico')),
                ('tipoAte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web_Taller_Mecánico.especialidad')),
            ],
        ),
    ]
