# Generated by Django 4.1.5 on 2023-07-05 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Taller_Mecánico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('idGaleria', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(upload_to='foto')),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web_Taller_Mecánico.regate')),
            ],
        ),
    ]
